apiVersion: v1
entries:
  keda-kaito-scaler:
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2025-11-03T03:25:43.532048184Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: e0b4856867a368fba6a9bc2cbed825dbd8f3712a7f099d646ca8c78e886fed8d
    name: keda-kaito-scaler
    type: application
    urls:
    - https://raw.githubusercontent.com/kaito-project/keda-kaito-scaler/main/charts/v0.0.1/keda-kaito-scaler-0.0.1.tgz
    version: 0.0.1
generated: "2025-11-03T03:25:43.531681208Z"
