apiVersion: v1
entries:
  keda-kaito-scaler:
  - apiVersion: v2
    appVersion: v0.3.0
    created: "2025-11-24T04:05:47.698109017Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: 6e0e50937ead407766bf4566912c7e6bed0f375c922326cc57cf3d5d90259a05
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2025-11-07T07:09:57.06807353Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: ea5e3df12527485265bbac66af851a3931fdd1f4543843e4ba349bfdaa9abc85
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2025-08-29T07:25:49.178791572Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: 0dd856beaa286718276ad3f860cd1e5a55850f6df90e0c3a753a9cd5ed532af1
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.0.1.tgz
    version: 0.0.1
generated: "2025-11-24T04:05:47.69734721Z"
