---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: keda-kaito-scaler-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: keda-kaito-scaler-svc
        namespace: kaito-workspace
        path: /mutate-keda-sh-v1alpha1-scaledobject
    failurePolicy: Ignore
    name: mutating.scaledobjects.kaito.sh
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - scaledobjects
    sideEffects: None
