log:
  level: 5

replicaCount: 1
certDuration: 26280h
nameOverrider: ""

image:
    registry: ghcr.io
    repository: kaito-project/keda-kaito-scaler
    tag: 0.3.0
    pullSecrets: []

ports:
  grpc: 10450
  metrics: 10451
  healthProbe: 10453

resources:
  limits:
    cpu: 2000m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
  